services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=${NGROK_URL}  # Utilise l'URL ngrok ici si nécessaire
    stdin_open: true
    tty: true
