services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin_client
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env 
    stdin_open: true
    tty: true
